workflows:
  dev-android:
    name: build, test & publish Android version
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.16.0
      xcode: latest
      android_signing:
        - devfest23-key
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      branch_patterns:
        - pattern: 'dev'
          include: true
      events:
        - push
      cancel_previous_builds: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Widgetbook generator
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Flutter analyze
        ignore_failure: true
        script: |
          flutter analyze .
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build app binary
        script: |
          flutter build apk --release -t lib/main_prod.dart --obfuscate --split-debug-info=.    
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - abadasamuelosp@gmail.com
          - sebastinesoacatp@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
