name: devfest23
description: iOS and Android app for Devfest Lagos 2023, built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  flutter_riverpod: ^2.3.6
  flutter_native_splash: ^2.3.1
  equatable: ^2.0.5
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  widgetbook: ^3.1.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSansDisplay-Bold.ttf
        - asset: assets/fonts/GoogleSansDisplay-Regular.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages